<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: /mnt/c/Users/abell/Documents/GitHub/NRE-Memory/src/Memory/Manager/Data/NRE_Memory.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_223fe3ddb66d6cdaa34448ac551f01ae.php">Memory</a></li><li class="navelem"><a class="el" href="dir_0c32b5ef650ca1c7db8bcb9d38c8a3da.php">Manager</a></li><li class="navelem"><a class="el" href="dir_c0269c0cbe16e36c5767a8e54f6ff782.php">Data</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Memory.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_memory_2_manager_2_data_2_n_r_e___memory_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;    </div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___memory_helper_8hpp.php">NRE_MemoryHelper.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    </div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_memory.php">Memory</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;            </div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory.php">   30</a></span>&#160;            <span class="keyword">class </span><a class="code" href="namespace_memory.php">Memory</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory.php#ac16541a849ddb56c20f7a86cceda80fb">   37</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_memory.php#ac16541a849ddb56c20f7a86cceda80fb">Memory</a>(<span class="keywordtype">void</span>* d) : <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>(d) {</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                        }</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00044"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">   44</a></span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">free</a>()<span class="keyword"> override </span>{</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                            std::cout &lt;&lt; <span class="stringliteral">&quot;Deallocating and Deconstruct : &quot;</span> &lt;&lt; <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a> &lt;&lt; std::endl;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                            T* typed = static_cast &lt;T*&gt; (<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a>);</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                            typed-&gt;~T();</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">::free</a>(typed);</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a> = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                        }</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            };</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    </div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;            <span class="keyword">template</span> &lt;&gt;</div><div class="line"><a name="l00058"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php">   58</a></span>&#160;            <span class="keyword">class </span><a class="code" href="namespace_memory.php">Memory</a>&lt;void&gt; : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a> {</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00065"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#a000e3731b80015dd6e9cf2c6c059dbb4">   65</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#a000e3731b80015dd6e9cf2c6c059dbb4">Memory</a>(<span class="keywordtype">void</span>* d) : <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>(d) {</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                        }</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;            </div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00072"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#ab4ab52fa8b31cef1f27d0b5aeaa7b2dc">   72</a></span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#ab4ab52fa8b31cef1f27d0b5aeaa7b2dc">free</a>()<span class="keyword"> override </span>{</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                            std::cout &lt;&lt; <span class="stringliteral">&quot;Deallocating but can&#39;t deconstruct : &quot;</span> &lt;&lt; <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a> &lt;&lt; std::endl;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">::free</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a>);</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a> = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                        }</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;            };</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;        </div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        }</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php">NRE::Memory::MemoryHelper</a></div><div class="ttdoc">Store a memory pointer, need to be used from derived class. </div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4_php_a000e3731b80015dd6e9cf2c6c059dbb4"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#a000e3731b80015dd6e9cf2c6c059dbb4">NRE::Memory::Memory&lt; void &gt;::Memory</a></div><div class="ttdeci">Memory(void *d)</div><div class="ttdef"><b>Definition:</b> NRE_Memory.hpp:65</div></div>
<div class="ttc" id="namespace_memory_php"><div class="ttname"><a href="namespace_memory.php">Memory</a></div><div class="ttdoc">Memory&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a931d45f5fa663a18b21f8f5c99e1c242"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">NRE::Memory::MemoryHelper::data</a></div><div class="ttdeci">void * data</div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:31</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="_n_r_e___memory_helper_8hpp_php"><div class="ttname"><a href="_n_r_e___memory_helper_8hpp.php">NRE_MemoryHelper.hpp</a></div><div class="ttdoc">Declaration of Memory&amp;#39;s API&amp;#39;s Object : MemoryHelper. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_php_ac16541a849ddb56c20f7a86cceda80fb"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory.php#ac16541a849ddb56c20f7a86cceda80fb">NRE::Memory::Memory::Memory</a></div><div class="ttdeci">Memory(void *d)</div><div class="ttdef"><b>Definition:</b> NRE_Memory.hpp:37</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4_php_ab4ab52fa8b31cef1f27d0b5aeaa7b2dc"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#ab4ab52fa8b31cef1f27d0b5aeaa7b2dc">NRE::Memory::Memory&lt; void &gt;::free</a></div><div class="ttdeci">void free() override</div><div class="ttdef"><b>Definition:</b> NRE_Memory.hpp:72</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_php_a889a76a7e78e8620c19cf13c9d5ebc90"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">NRE::Memory::Memory::free</a></div><div class="ttdeci">void free() override</div><div class="ttdef"><b>Definition:</b> NRE_Memory.hpp:44</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
