<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: /mnt/c/Users/abell/Documents/GitHub/NRE-Memory/src/Memory/Allocator/Default/NRE_DefaultAllocator.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_223fe3ddb66d6cdaa34448ac551f01ae.php">Memory</a></li><li class="navelem"><a class="el" href="dir_90418763254490afbe31fb653731f493.php">Allocator</a></li><li class="navelem"><a class="el" href="dir_1a391fadf0f63e8314d648c415e0ad4e.php">Default</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_DefaultAllocator.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___default_allocator_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;cassert&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;memory&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &quot;../NRE_AllocatorTraits.hpp&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;    </div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_memory.php">Memory</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        </div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">   32</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">DefaultAllocator</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_allocator_traits.php">AllocatorTraits</a>&lt;DefaultAllocator&lt;T&gt;&gt; {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Traits</span></div><div class="line"><a name="l00035"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8371653e924ca448e5923a97989a450b">   35</a></span>&#160;<span class="comment"></span>                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_allocator_traits.php">Traits</a> = <a class="code" href="class_n_r_e_1_1_memory_1_1_allocator_traits.php">AllocatorTraits&lt;DefaultAllocator&lt;T&gt;</a>&gt;;</div><div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a45284e27381356bba10f0199a83ae9d7">   37</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a45284e27381356bba10f0199a83ae9d7">ValueType</a>     = <span class="keyword">typename</span> Traits::ValueType;</div><div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">   39</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">Pointer</a>       = <span class="keyword">typename</span> Traits::Pointer;</div><div class="line"><a name="l00041"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#afbf052bb7b3e436082c766deb95e80a9">   41</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#afbf052bb7b3e436082c766deb95e80a9">ConstPointer</a>  = <span class="keyword">typename</span> Traits::ConstPointer;</div><div class="line"><a name="l00043"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ac1e05995ba31cba1bb617dfe66ad1039">   43</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ac1e05995ba31cba1bb617dfe66ad1039">SizeType</a>      = <span class="keyword">typename</span> Traits::SizeType;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Methods</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#adc2634bd4d47a2b862bb444732dceaeb">DefaultAllocator</a>() noexcept = default;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;                        </div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                    <span class="comment">//## Convertor ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        template &lt;class K&gt;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                        <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">DefaultAllocator</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">DefaultAllocator</a>&lt;K&gt; const&amp; alloc) noexcept;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                        </div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;<span class="comment"></span>                        [[nodiscard]] <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">Pointer</a> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a9b3cbddea4785bb6fb04d48b896f18e1">allocate</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ac1e05995ba31cba1bb617dfe66ad1039">SizeType</a> n = 1);</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8cc22e61037fa1a5d1690638ab44bb65">deallocate</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">Pointer</a> p);</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8cc22e61037fa1a5d1690638ab44bb65">deallocate</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">Pointer</a> p, <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ac1e05995ba31cba1bb617dfe66ad1039">SizeType</a> n);</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                        template &lt;class K, class ... Args&gt;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                        K* <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#aacfc9d6880c15355f1ba8ab57535ecd0">construct</a>(K* p, Args &amp;&amp; ... args);</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                        template &lt;class K&gt;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                        K* <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8145d9f7fa7e362f6d85e6f2301f6a48">destroy</a>(K* p);</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;            };</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;            </div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;            <span class="preprocessor">#ifndef NRE_USE_MEMORY_MANAGER</span></div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00098"></a><span class="lineno"><a class="line" href="_n_r_e___default_allocator_8hpp.php#ac9b8e00aef5813dd45e7df7c34489ece">   98</a></span>&#160;                <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">Allocator</a> = <a class="code" href="class_n_r_e_1_1_memory_1_1_default_allocator.php">DefaultAllocator&lt;T&gt;</a>;</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;<span class="preprocessor">            #endif</span></div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;            </div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;        }</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;    }</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;<span class="preprocessor">    #include &quot;NRE_DefaultAllocator.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_a8cc22e61037fa1a5d1690638ab44bb65"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8cc22e61037fa1a5d1690638ab44bb65">NRE::Memory::DefaultAllocator::deallocate</a></div><div class="ttdeci">void deallocate(Pointer p)</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_allocator_traits_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_allocator_traits.php">NRE::Memory::AllocatorTraits</a></div><div class="ttdoc">Describe an allocator object. </div><div class="ttdef"><b>Definition:</b> NRE_AllocatorTraits.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_adc2634bd4d47a2b862bb444732dceaeb"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#adc2634bd4d47a2b862bb444732dceaeb">NRE::Memory::DefaultAllocator::DefaultAllocator</a></div><div class="ttdeci">DefaultAllocator() noexcept=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_a8145d9f7fa7e362f6d85e6f2301f6a48"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8145d9f7fa7e362f6d85e6f2301f6a48">NRE::Memory::DefaultAllocator::destroy</a></div><div class="ttdeci">K * destroy(K *p)</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_aacfc9d6880c15355f1ba8ab57535ecd0"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#aacfc9d6880c15355f1ba8ab57535ecd0">NRE::Memory::DefaultAllocator::construct</a></div><div class="ttdeci">K * construct(K *p, Args &amp;&amp;...args)</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_ac1e05995ba31cba1bb617dfe66ad1039"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ac1e05995ba31cba1bb617dfe66ad1039">NRE::Memory::DefaultAllocator::SizeType</a></div><div class="ttdeci">typename Traits::SizeType SizeType</div><div class="ttdef"><b>Definition:</b> NRE_DefaultAllocator.hpp:43</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_afbf052bb7b3e436082c766deb95e80a9"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#afbf052bb7b3e436082c766deb95e80a9">NRE::Memory::DefaultAllocator::ConstPointer</a></div><div class="ttdeci">typename Traits::ConstPointer ConstPointer</div><div class="ttdef"><b>Definition:</b> NRE_DefaultAllocator.hpp:41</div></div>
<div class="ttc" id="namespace_memory_php"><div class="ttname"><a href="namespace_memory.php">Memory</a></div><div class="ttdoc">Memory&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_a45284e27381356bba10f0199a83ae9d7"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a45284e27381356bba10f0199a83ae9d7">NRE::Memory::DefaultAllocator::ValueType</a></div><div class="ttdeci">typename Traits::ValueType ValueType</div><div class="ttdef"><b>Definition:</b> NRE_DefaultAllocator.hpp:37</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_a55cdfb77ac670c7f0f354c4520e1d75f"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a55cdfb77ac670c7f0f354c4520e1d75f">NRE::Memory::DefaultAllocator::Pointer</a></div><div class="ttdeci">typename Traits::Pointer Pointer</div><div class="ttdef"><b>Definition:</b> NRE_DefaultAllocator.hpp:39</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php">NRE::Memory::DefaultAllocator</a></div><div class="ttdoc">Default allocator using global new and delete. </div><div class="ttdef"><b>Definition:</b> NRE_DefaultAllocator.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_default_allocator_php_a9b3cbddea4785bb6fb04d48b896f18e1"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a9b3cbddea4785bb6fb04d48b896f18e1">NRE::Memory::DefaultAllocator::allocate</a></div><div class="ttdeci">Pointer allocate(SizeType n=1)</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
