<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: /mnt/c/Users/abell/Documents/GitHub/NRE-Memory/src/Memory/Manager/NRE_MemoryManager.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_223fe3ddb66d6cdaa34448ac551f01ae.php">Memory</a></li><li class="navelem"><a class="el" href="dir_0c32b5ef650ca1c7db8bcb9d38c8a3da.php">Manager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_MemoryManager.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___memory_manager_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;    </div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;algorithm&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;Utility/Singleton/NRE_Singleton.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;Utility/Detail/Vector/NRE_Vector.hpp&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../Allocator/Direct/NRE_DirectAllocator.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_memory_2_manager_2_data_2_n_r_e___memory_8hpp.php">Data/NRE_Memory.hpp</a>&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    </div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_memory.php">Memory</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_manager.php">   34</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_memory_1_1_memory_manager.php">MemoryManager</a>  : <span class="keyword">public</span> Utility::Singleton&lt;MemoryManager&gt; {</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                <span class="keyword">friend</span> <span class="keyword">class </span>Singleton&lt;MemoryManager&gt;;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                <span class="keyword">private</span>:    <span class="comment">// Fields</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    Utility::Detail::Vector&lt;MemoryHelper*, DirectAllocator&lt;MemoryHelper*&gt;&gt; allocated;   </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a88977c69bf179914fdf44ca29d420cfa">   46</a></span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a88977c69bf179914fdf44ca29d420cfa">storeMemory</a>(T* data) {</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php">DirectAllocator&lt;Memory&lt;T&gt;</a>&gt; alloc;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                            allocated.emplaceBack(alloc.<a class="code" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a844222c73953e74882ff52e6b6eebc42">construct</a>(alloc.<a class="code" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a3d392899c6e8f7575aa641fcd434e9e6">allocate</a>(1), data));</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                        }</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00055"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#adb396c53f7b64f8b92880463dc56d6a5">   55</a></span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#adb396c53f7b64f8b92880463dc56d6a5">removeMemory</a>(T* data) {</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                            <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>* toRemove = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                            <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>* mem : allocated) {</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                                <span class="keywordflow">if</span> (mem-&gt;getData() == data) {</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                                    toRemove = mem;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                                    <span class="keywordflow">break</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                                }</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                            }</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                            <span class="keywordflow">if</span> (toRemove != <span class="keyword">nullptr</span>) {</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                                allocated.erase(std::remove(allocated.begin(), allocated.end(), toRemove), allocated.end());</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                                <span class="keyword">delete</span> toRemove;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                            }</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                        }</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        </div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                <span class="keyword">private</span>:   <span class="comment">// Methods</span></div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="comment"></span>                        MemoryManager() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;            </div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        ~MemoryManager() {</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                            <span class="keywordflow">if</span> (allocated.isEmpty()) {</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                                std::cout &lt;&lt; <span class="stringliteral">&quot;Everything&#39;s fine !&quot;</span> &lt;&lt; std::endl;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                            } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>* p : allocated) {</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                                    std::cout &lt;&lt; <span class="stringliteral">&quot;Memory at : &quot;</span> &lt;&lt; p-&gt;<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">getData</a>() &lt;&lt; <span class="stringliteral">&quot; has not been freed !&quot;</span> &lt;&lt; std::endl;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                                    p-&gt;free();</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;            </div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;                                    p-&gt;~MemoryHelper();</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                                    free(p);</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                                }</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                            }</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                        }</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                    </div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Static</span></div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;<span class="comment"></span>                    <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00100"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a78ea393083fcc8f85e2160f830c1dd8d">  100</a></span>&#160;                    <span class="keyword">static</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a78ea393083fcc8f85e2160f830c1dd8d">store</a>(T* data) {</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        Utility::Singleton&lt;MemoryManager&gt;::get().storeMemory(data);</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                    }</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                    <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00108"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a106b7a020213d42ae655b1f683332538">  108</a></span>&#160;                    <span class="keyword">static</span> <span class="keywordtype">void</span> <span class="keyword">remove</span>(T* data) {</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                        Utility::Singleton&lt;MemoryManager&gt;::get().removeMemory(data);</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;                    }</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;            };</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;            </div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;        }</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php">NRE::Memory::MemoryHelper</a></div><div class="ttdoc">Store a memory pointer, need to be used from derived class. </div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_manager_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_manager.php">NRE::Memory::MemoryManager</a></div><div class="ttdoc">Store current allocated memory and tell if any memory leak occurs. </div><div class="ttdef"><b>Definition:</b> NRE_MemoryManager.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_direct_allocator_php_a844222c73953e74882ff52e6b6eebc42"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a844222c73953e74882ff52e6b6eebc42">NRE::Memory::DirectAllocator::construct</a></div><div class="ttdeci">K * construct(K *p, Args &amp;&amp;...args)</div></div>
<div class="ttc" id="_memory_2_manager_2_data_2_n_r_e___memory_8hpp_php"><div class="ttname"><a href="_memory_2_manager_2_data_2_n_r_e___memory_8hpp.php">NRE_Memory.hpp</a></div><div class="ttdoc">Declaration of Memory&amp;#39;s API&amp;#39;s Object : Memory. </div></div>
<div class="ttc" id="namespace_memory_php"><div class="ttname"><a href="namespace_memory.php">Memory</a></div><div class="ttdoc">Memory&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_direct_allocator_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_direct_allocator.php">NRE::Memory::DirectAllocator</a></div><div class="ttdoc">Allocate memory using malloc and free directly. </div><div class="ttdef"><b>Definition:</b> NRE_DirectAllocator.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_manager_php_a78ea393083fcc8f85e2160f830c1dd8d"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a78ea393083fcc8f85e2160f830c1dd8d">NRE::Memory::MemoryManager::store</a></div><div class="ttdeci">static void store(T *data)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryManager.hpp:100</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a48a9ae66560f9c35941d5bcf47a128e5"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">NRE::Memory::MemoryHelper::getData</a></div><div class="ttdeci">void * getData() const </div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:61</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_direct_allocator_php_a3d392899c6e8f7575aa641fcd434e9e6"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a3d392899c6e8f7575aa641fcd434e9e6">NRE::Memory::DirectAllocator::allocate</a></div><div class="ttdeci">Pointer allocate(SizeType n=1)</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_manager_php_a88977c69bf179914fdf44ca29d420cfa"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a88977c69bf179914fdf44ca29d420cfa">NRE::Memory::MemoryManager::storeMemory</a></div><div class="ttdeci">void storeMemory(T *data)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryManager.hpp:46</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_manager_php_adb396c53f7b64f8b92880463dc56d6a5"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_manager.php#adb396c53f7b64f8b92880463dc56d6a5">NRE::Memory::MemoryManager::removeMemory</a></div><div class="ttdeci">void removeMemory(T *data)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryManager.hpp:55</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
