<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: /mnt/c/Users/abell/Documents/GitHub/NRE-Memory/src/Memory/Manager/Data/NRE_MemoryHelper.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_223fe3ddb66d6cdaa34448ac551f01ae.php">Memory</a></li><li class="navelem"><a class="el" href="dir_0c32b5ef650ca1c7db8bcb9d38c8a3da.php">Manager</a></li><li class="navelem"><a class="el" href="dir_c0269c0cbe16e36c5767a8e54f6ff782.php">Data</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_MemoryHelper.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___memory_helper_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">#include &lt;Utility/Interfaces/Uncopyable/NRE_Uncopyable.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    </div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_memory.php">Memory</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;            </div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">   29</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a> : <span class="keyword">public</span> Utility::Uncopyable&lt;MemoryHelper&gt; {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keyword">protected</span> : <span class="comment">// Fields</span></div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">   31</a></span>&#160;                    <span class="keywordtype">void</span>* <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a>; </div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#aba2fc0b8ec9e9e8fed7db31bd3b6d25e">   39</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#aba2fc0b8ec9e9e8fed7db31bd3b6d25e">MemoryHelper</a>(<span class="keywordtype">void</span>* d) : data(d) {</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                        }</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00047"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a8ef572dbda6051612de78c8d5ff33cad">   47</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a8ef572dbda6051612de78c8d5ff33cad">MemoryHelper</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a> &amp;&amp; m) : data(m.data) {</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                            m.data = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                        }</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                    </div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#ab101312e57c8f2d0f5b98534f88f57ac">~MemoryHelper</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;    </div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">   61</a></span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span>* <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">getData</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                            <span class="keywordflow">return</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a>;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                        }</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    </div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a7682a33118461ea406c6b9a9f2f6b129">free</a>() = 0;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    </div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a1c2995adac2cf17a711975b50daeb3d0">   77</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a>&amp; <a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a1c2995adac2cf17a711975b50daeb3d0">operator =</a>(<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php">MemoryHelper</a> &amp;&amp; m) {</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                            <span class="keywordflow">if</span> (<span class="keyword">this</span> != &amp;m) {</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                                data = m.<a class="code" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">data</a>;</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;                                m.data = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                            }</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                            <span class="keywordflow">return</span> *<span class="keyword">this</span>;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                        }</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;            };</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        </div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;        }</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php">NRE::Memory::MemoryHelper</a></div><div class="ttdoc">Store a memory pointer, need to be used from derived class. </div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:29</div></div>
<div class="ttc" id="namespace_memory_php"><div class="ttname"><a href="namespace_memory.php">Memory</a></div><div class="ttdoc">Memory&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a931d45f5fa663a18b21f8f5c99e1c242"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a931d45f5fa663a18b21f8f5c99e1c242">NRE::Memory::MemoryHelper::data</a></div><div class="ttdeci">void * data</div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:31</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a7682a33118461ea406c6b9a9f2f6b129"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a7682a33118461ea406c6b9a9f2f6b129">NRE::Memory::MemoryHelper::free</a></div><div class="ttdeci">virtual void free()=0</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a48a9ae66560f9c35941d5bcf47a128e5"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">NRE::Memory::MemoryHelper::getData</a></div><div class="ttdeci">void * getData() const </div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:61</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a8ef572dbda6051612de78c8d5ff33cad"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a8ef572dbda6051612de78c8d5ff33cad">NRE::Memory::MemoryHelper::MemoryHelper</a></div><div class="ttdeci">MemoryHelper(MemoryHelper &amp;&amp;m)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:47</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_ab101312e57c8f2d0f5b98534f88f57ac"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#ab101312e57c8f2d0f5b98534f88f57ac">NRE::Memory::MemoryHelper::~MemoryHelper</a></div><div class="ttdeci">virtual ~MemoryHelper()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_a1c2995adac2cf17a711975b50daeb3d0"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a1c2995adac2cf17a711975b50daeb3d0">NRE::Memory::MemoryHelper::operator=</a></div><div class="ttdeci">MemoryHelper &amp; operator=(MemoryHelper &amp;&amp;m)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:77</div></div>
<div class="ttc" id="class_n_r_e_1_1_memory_1_1_memory_helper_php_aba2fc0b8ec9e9e8fed7db31bd3b6d25e"><div class="ttname"><a href="class_n_r_e_1_1_memory_1_1_memory_helper.php#aba2fc0b8ec9e9e8fed7db31bd3b6d25e">NRE::Memory::MemoryHelper::MemoryHelper</a></div><div class="ttdeci">MemoryHelper(void *d)</div><div class="ttdef"><b>Definition:</b> NRE_MemoryHelper.hpp:39</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
