<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li class="current"><a href="#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>allocate()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#a9f01ece6d7a56473b2b378116c4b281a">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a9b3cbddea4785bb6fb04d48b896f18e1">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a3d392899c6e8f7575aa641fcd434e9e6">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#aee7599743acb3350f16e683e3695c40f">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>construct()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#a1a7cc004b9c731bb620a1ec261a0a277">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#aacfc9d6880c15355f1ba8ab57535ecd0">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a844222c73953e74882ff52e6b6eebc42">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#aef04e456ef2a827949953f5c57fabe5e">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>deallocate()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#afa9d2cef262827294a84fac7e3cc7b40">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8cc22e61037fa1a5d1690638ab44bb65">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#acc82a7c5e0b15af22d868c7bbedd1893">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#af5a255cfd3d195e1e02e883e37a6c292">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>DefaultAllocator()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#adc2634bd4d47a2b862bb444732dceaeb">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
</li>
<li>destroy()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#a9fde1294b99e6d45bea2638dfb0eb896">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a8145d9f7fa7e362f6d85e6f2301f6a48">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a0477d4f06aa77d3dac88abc9ad50d93b">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#a2a04f835dc84a14445f1efa7e6091c3b">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>DirectAllocator()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a5195ffec203189788822010d2292fedd">NRE::Memory::DirectAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>free()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">NRE::Memory::Memory&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#ab4ab52fa8b31cef1f27d0b5aeaa7b2dc">NRE::Memory::Memory&lt; void &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a7682a33118461ea406c6b9a9f2f6b129">NRE::Memory::MemoryHelper</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getAddress()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#a206d2739b7cb99d27af15b226d2eeb71">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
</li>
<li>getData()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">NRE::Memory::MemoryHelper</a>
</li>
<li>getMaxSize()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_allocator_traits_3_01_alloc_3_01_t_00_01_alloc_args_8_8_8_01_4_01_4.php#a6781b6da52549beb2df1a91013a377bf">NRE::Memory::AllocatorTraits&lt; Alloc&lt; T, AllocArgs... &gt; &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>ManagerAllocator()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#ac48608f8fb4cc048df2b65e10a050156">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>Memory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory.php#ac16541a849ddb56c20f7a86cceda80fb">NRE::Memory::Memory&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#a000e3731b80015dd6e9cf2c6c059dbb4">NRE::Memory::Memory&lt; void &gt;</a>
</li>
<li>MemoryHelper()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#aba2fc0b8ec9e9e8fed7db31bd3b6d25e">NRE::Memory::MemoryHelper</a>
</li>
<li>MemoryManager()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a29c0c5f666e66b540830b47a3e20a00c">NRE::Memory::MemoryManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a1c2995adac2cf17a711975b50daeb3d0">NRE::Memory::MemoryHelper</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>remove()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a106b7a020213d42ae655b1f683332538">NRE::Memory::MemoryManager</a>
</li>
<li>removeMemory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#adb396c53f7b64f8b92880463dc56d6a5">NRE::Memory::MemoryManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>store()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a78ea393083fcc8f85e2160f830c1dd8d">NRE::Memory::MemoryManager</a>
</li>
<li>storeMemory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a88977c69bf179914fdf44ca29d420cfa">NRE::Memory::MemoryManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_0x7e"></a>- ~ -</h3><ul>
<li>~MemoryHelper()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#ab101312e57c8f2d0f5b98534f88f57ac">NRE::Memory::MemoryHelper</a>
</li>
<li>~MemoryManager()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a18fadf7c0b4243bf09ff0bd412df7bd7">NRE::Memory::MemoryManager</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
