<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Memory: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li class="current"><a href="#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>allocate()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a7128011ad5ef6d499ca88a32a81c76d2">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#af164ce84938bbccd55bc40e84934b62e">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#af13b76e1e481d9ecbe1bda7b6ab080fa">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#ab8095072b53d13d3c20da79d73f58ae2">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>construct()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#aacfc9d6880c15355f1ba8ab57535ecd0">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a844222c73953e74882ff52e6b6eebc42">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#a2ef035d639ca3994c4871f4131bfb9e2">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#aef04e456ef2a827949953f5c57fabe5e">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>deallocate()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ae3d6eee0e0216db63b387e1cd9d06f2b">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a318cf1b70716a4fa4e72a25a98e1bc57">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#ad05fa4c8c1085707f4b912db2ca667d7">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#ae34c887d9f641cc7efa37b8a68914140">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>destroy()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a93874628a47cd3975bef4c7ae56ba6d7">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a021280fc327c81a9881e4d6c29acde5e">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#a8bde0f4fe8ca99fe9aede3081707f566">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#a4ddee56a5270f2c5ea7d7af7ef43ef37">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>equal()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#ab1afb48bf0b832e84184aba39aea2385">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#ae962c2214146350e72864d7a66828072">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#af914d6e43b0d6056e777a008168f3cc7">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>free()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory.php#a889a76a7e78e8620c19cf13c9d5ebc90">NRE::Memory::Memory&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#ab4ab52fa8b31cef1f27d0b5aeaa7b2dc">NRE::Memory::Memory&lt; void &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a7682a33118461ea406c6b9a9f2f6b129">NRE::Memory::MemoryHelper</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getAddress()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a48e1c8ca549bdf4297b4625dfa098fac">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a0a3aaf395eeb5caaad2f3ae3c5580611">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#a546ef27c17d2c2a034abd989526f9770">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#a4ff3bca65630fb09bd8b48e3a5059ba5">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>getData()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a48a9ae66560f9c35941d5bcf47a128e5">NRE::Memory::MemoryHelper</a>
</li>
<li>getMaxSize()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a5d2071b8181bf81257d4a5bd5994b001">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#ac8014229d6a6492e1968a025353b89b3">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#ae1f04ef5ff7a1504f30c433fa6106916">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#a3917736f2868992e5a93951224b688f6">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>Memory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory.php#ac16541a849ddb56c20f7a86cceda80fb">NRE::Memory::Memory&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_3_01void_01_4.php#a000e3731b80015dd6e9cf2c6c059dbb4">NRE::Memory::Memory&lt; void &gt;</a>
</li>
<li>MemoryHelper()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#aba2fc0b8ec9e9e8fed7db31bd3b6d25e">NRE::Memory::MemoryHelper</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>operator!=()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#a7b8c5e96992902982e90bfa006a23e52">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a727537922d07b8d6f2434593c361de3a">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#ac27e2268a23a2feb285bb956cc267a1f">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#abd34092db03d68400985d64e24337386">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#a1c2995adac2cf17a711975b50daeb3d0">NRE::Memory::MemoryHelper</a>
</li>
<li>operator==()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_default_allocator.php#aed4e9d9699f151163b47b55f8f26d300">NRE::Memory::DefaultAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_direct_allocator.php#a90465dfca3f08f978514dc76c2cdf27b">NRE::Memory::DirectAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_i_allocator.php#a096981a3600ebc03140c9345482acb04">NRE::Memory::IAllocator&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_memory_1_1_manager_allocator.php#aa344b1b80f5c2490de56f3098e29739c">NRE::Memory::ManagerAllocator&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>removeMemory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#adb396c53f7b64f8b92880463dc56d6a5">NRE::Memory::MemoryManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>storeMemory()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_manager.php#a88977c69bf179914fdf44ca29d420cfa">NRE::Memory::MemoryManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_0x7e"></a>- ~ -</h3><ul>
<li>~MemoryHelper()
: <a class="el" href="class_n_r_e_1_1_memory_1_1_memory_helper.php#ab101312e57c8f2d0f5b98534f88f57ac">NRE::Memory::MemoryHelper</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
